// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL-GzfHn8oQA0lLjw6p2R8w3RagN2Qyfg',
    appId: '1:860082283576:web:7fec47f5e11f83c029b2cd',
    messagingSenderId: '860082283576',
    projectId: 'image-916e0',
    authDomain: 'image-916e0.firebaseapp.com',
    storageBucket: 'image-916e0.appspot.com',
    measurementId: 'G-JH1RXBB1QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKRNfDfgZCi_AOJzsRIqX-qdlg6kWa32E',
    appId: '1:860082283576:android:6570f0469aeb40a929b2cd',
    messagingSenderId: '860082283576',
    projectId: 'image-916e0',
    storageBucket: 'image-916e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6bHrhdkL1Sfgk_9NxOB_tv6Jszr7Tkio',
    appId: '1:860082283576:ios:6327f1999f70979829b2cd',
    messagingSenderId: '860082283576',
    projectId: 'image-916e0',
    storageBucket: 'image-916e0.appspot.com',
    iosBundleId: 'com.example.form',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6bHrhdkL1Sfgk_9NxOB_tv6Jszr7Tkio',
    appId: '1:860082283576:ios:9bbd39353309452429b2cd',
    messagingSenderId: '860082283576',
    projectId: 'image-916e0',
    storageBucket: 'image-916e0.appspot.com',
    iosBundleId: 'com.example.form.RunnerTests',
  );
}
